apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "niagara.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "niagara.labels" . | nindent 4 }}
spec:
  replicas:
  selector:
    matchLabels:
      app: {{ include "niagara.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "niagara.fullname" . }}
    spec:
      containers:
      - name: niagara
        image: {{ .Values.niagara.image }}:{{ .Values.niagara.tag }}
        tty: true
        ports:
        - name: platform-port
          protocol: TCP
          containerPort: {{ .Values.niagara.platformPort }}
        - name: station-port
          protocol: TCP
          containerPort: {{ .Values.niagara.stationPort }}
      {{- if .Values.nginx.enabled }}
      - name: nginx
        image: {{ .Values.nginx.image }}:{{.Values.nginx.tag }}
        ports:
          - name: http-port
            protocol: TCP
            containerPort: {{ .Values.nginx.containerPort }}
            hostPort: {{ .Values.nginx.containerPort }}
      {{- end }}
