apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-n4-ingress
  namespace: default
spec:
  dnsNames:
  - n4.ibb-01.test.cns.dev
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: letsencrypt
  secretName: tls-n4-ingress
