namespace: default

niagara:
  image: mindovermiles262/niagara
  tag: "0.0.3"
  port: 443
  version: "4.12.0.156"
  platformPort: 5011
  stationPort: 4911

nginx:
  enabled: false
  image: nginx
  tag: latest
  containerPort: 80

ingress:
  enabled: true
  sslRedirect: false
  className: traefik

certManager:
  enabled: true
  issuerName: letsencrypt
